### ISSUE TITLE
pool.maxSockets 参数并未生效

### ISSUE THREAD

**Issue by isayme** [teambition/tws-tcm#3]
![image](https://user-images.githubusercontent.com/1747852/33817011-fde3b786-de77-11e7-85a2-bccc80e090c9.png)

**Comment by isayme** [comment]
@DavidCai1993

**Comment by isayme** [comment]
@DavidCai1993 打个新版本吧.

**Comment by isayme** [comment]
@DavidCai1993 tws-auth 存在同样的问题

**Comment by DavidCai1993** [comment]
好

**Comment by DavidCai1993** [comment]
@isayme 0.8.2
